login_thd 用例运行失败,请检查！
Traceback (most recent call last):
  File "po\ExcuteCase.py", line 22, in wrapper
    func(*args, **kwargs)
  File "d:\python27\lib\site-packages\allure\common.py", line 62, in impl
    return func(*a, **kw)
  File "D:\lzm-demo\ui_auto\testcase\test_004_login_thd.py", line 43, in login_thd
    assert d(resourceId="com.chinamobile.cloudapp:id/home_cloud_title").get_text=="登录和我看"
AssertionError: assert <bound method UiObject.get_text of <uiautomator2.UiObject object at 0x04209430>> == '\xe7\x99\xbb\xe5\xbd\x95\xe5\x92\x8c\xe6\x88\x91\xe7\x9c\x8b'
 +  where <bound method UiObject.get_text of <uiautomator2.UiObject object at 0x04209430>> = <uiautomator2.UiObject object at 0x04209430>.get_text
 +    where <uiautomator2.UiObject object at 0x04209430> = uiautomator2 object for 192.168.1.19:7912(resourceId='com.chinamobile.cloudapp:id/home_cloud_title')

